# Generated by Django 4.2.7 on 2023-12-04 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Designing cloud based system', 'Designing cloud based system'), ('Advanced date managment', 'Advanced date managment')], max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Module', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
