# Generated by Django 4.2.7 on 2023-12-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleRegisrationSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Code', models.CharField(max_length=100)),
                ('Credit', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('Availabity', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
