# Generated by Django 4.2.7 on 2023-12-05 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleRegisrationSystem', '0002_module_delete_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('name', models.CharField(max_length=30, primary_key='name', serialize=False)),
                ('startdate', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.CharField(choices=[('1 year', '1 year'), ('2 year', '2 year'), ('3 year', '3 year')], max_length=10)),
                ('details', models.TextField()),
            ],
        ),
    ]
