# Generated by Django 4.2.7 on 2023-12-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleRegisrationSystem', '0003_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='Availabity',
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ManyToManyField(related_name='modules', to='ModuleRegisrationSystem.course'),
        ),
    ]
