# Generated by Django 4.2.7 on 2023-12-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleRegisrationSystem', '0005_rename_course_module_courses_module_availbity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='courses',
            new_name='course',
        ),
    ]
