# Generated by Django 4.2.7 on 2023-12-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ModuleRegisrationSystem', '0006_rename_courses_module_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.AddField(
            model_name='module',
            name='Groups',
            field=models.ManyToManyField(related_name='modules', to='auth.group'),
        ),
    ]
