# Generated by Django 4.2.7 on 2023-12-11 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleRegisrationSystem', '0008_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='dOfRegistration',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
