# Generated by Django 4.2.7 on 2023-12-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleRegisrationSystem', '0009_registration_dofregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='model',
            new_name='module',
        ),
    ]
