"""
Django settings for ModuleApp project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-kiu)@d#vy(z*st13rarsv4@3^47p&$b@*gd5lx%(@j3m89$#l2'

WEBSITE_HOSTNAME = os.environ.get('WEBSITE_HOSTNAME', None)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = WEBSITE_HOSTNAME == None

if DEBUG:
    ALLOWED_HOSTS = []
else:
    ALLOWED_HOSTS = [WEBSITE_HOSTNAME]
    CSRF_TRUSTED_ORIGINS = [f'https://{WEBSITE_HOSTNAME}']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ModuleRegisrationSystem.apps.ModuleregisrationsystemConfig',
    'users.apps.UsersConfig',
    'crispy_forms',
    'crispy_bootstrap4',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ModuleApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ModuleApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE':os.environ['AZURE_DB_ENGINE'],
       	'NAME': os.environ['AZURE_DB_NAME'],
       	'PORT': os.environ['AZURE_DB_PORT'],
       	'HOST': os.environ['AZURE_DB_HOST'],
        'USER': os.environ['AZURE_DB_USER'],
        'PASSWORD': os.environ['AZURE_DB_PASSWORD'],
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

#STATIC_URL = 'static/'
#MEDIA_ROOT = BASE_DIR / 'media'
#MEDIA_URL = '/media/'

STORAGES = {
    'default': {
        "BACKEND": "storages.backends.azure_storage.AzureStorage",
        "OPTIONS": {
            "connection_string": "DefaultEndpointsProtocol=https;AccountName=c0013851dcbs;AccountKey=2zXe370Ddx/XMWP4M1f2XMYBs33kaqqS+E9+yMQGevqGNN8rzHbZZ3RFcwj8NS91440VNUmoqJ97+AStGAUWbA==;EndpointSuffix=core.windows.net",
            "azure_container": "media"
        },
    },
    "staticfiles": {
        "BACKEND": "storages.backends.azure_storage.AzureStorage",
        "OPTIONS": {
            "connection_string": "DefaultEndpointsProtocol=https;AccountName=c0013851dcbs;AccountKey=2zXe370Ddx/XMWP4M1f2XMYBs33kaqqS+E9+yMQGevqGNN8rzHbZZ3RFcwj8NS91440VNUmoqJ97+AStGAUWbA==;EndpointSuffix=core.windows.net",
            "azure_container": "static"
        },
    },
}

STATIC_URL = 'c0013851dcbs.blob.core.windows.net/static/'
MEDIA_URL = 'c0013851dcbs.blob.core.windows.net/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACK = 'bootstrap4'
CRISPY_TEMPLATE_PACK = 'bootstrap4'


LOGIN_REDIRECT_URL = 'ModuleRegisrationSystem:home'
LOGIN_URL = 'login'

SECRET_KEY = os.environ['SECRET_KEY']







